schema:
  - "https://carline.onrender.com"
documents:
  - "./src/**/*.ts"
generates:
  ./src/graphql/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo